name: Checks
on:
    push:
        branches: master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - 
                name: Checkout
                uses: actions/checkout@v2.4.0
            -
                name: check links
                run: find . \( -name "*.html" -o -name "*.xml" \) -type f -exec sh -c 'echo "Checking links in file: $0"; bin/check_links "$0"' {} \;
