name: Checks
on: [pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - 
                name: Checkout
                uses: actions/checkout@v2.4.0
            -
                name: Configure Java
                uses: actions/setup-java@v4.5.0
                with:
                    java-version: 17
                    distribution: temurin
            -
                name: Render Static Site
                run: bin/render
            -
                name: Check Output Links
                run: |
                    find build/output \( -name "*.html" -o -name "*.xml" \) -type f -exec sh -c 'echo "Checking links in file: $0"; bin/check_links "$0"' {} \;
