name: Pushes
on:
    push:
        branches: [master]
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            pages: write
        steps:
            - 
                name: Checkout
                uses: actions/checkout@v4.2.2
            -
                name: Configure Java
                uses: actions/setup-java@v5.0.0
                with:
                    java-version: 17
                    distribution: temurin
            -
                name: Render Static Site
                run: bin/render
            -
                name: Check Output Links
                run: |
                    find build/output \( -name "*.html" -o -name "*.xml" \) -type f -exec sh -c 'echo "Checking links in file: $0"; bin/check_links "$0"' {} \;
            -
                name: Upload Pages Artifact
                uses: actions/upload-pages-artifact@v3.0.1
                with:
                    path: build/output
            -
                name: Deploy to GitHub Pages
                uses: actions/deploy-pages@v4.0.5
